---
- name: Stop service systemd-resolved
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped

- name: Disable service systemd-resolved
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    enabled: no

- name: Remove symbol link resolv.conf
  become: true
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent

- name: resolv.conf | Ensure dns configuration
  become: true
  template:
    src: resolv.j2
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    mode: 0644

- name: Add hosts entries to /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ item.addr }} {{ item.domain }}"
    state: present
  loop: "{{ etc_hosts }}"
  when: etc_hosts | length > 0
  tags:
    - etc_hosts

- name: Remove - update_etc_hosts when update_etc_hosts is false
  ansible.builtin.lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^\s*-\s*update_etc_hosts\s*$'
    state: absent
  when: not (update_etc_hosts | bool)
  tags:
    - etc_hosts

- name: Ensure - update_etc_hosts exists when update_etc_hosts is true
  ansible.builtin.lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^\s*-\s*update_etc_hosts\s*$'
    line: '  - update_etc_hosts'
    insertafter: '^cloud_init_modules:'
  when: update_etc_hosts | bool
  tags:
    - etc_hosts
